import type { InfluencerStats } from '@/types';

// Mock data for development - will be replaced with API calls
export const mockInfluencers: InfluencerStats[] = [
    {
        username: "snag0716",
        totalTweets: 500,
        totalCalls: 312,
        successfulCalls: 309,
        failedCalls: 3,
        successRate: 99,
        totalRoi: 2970,
        avgRoi: 76,
        hypotheticalPnL: 29700,
        calls: [],
        score: 90126,
        rankChange: 0,
        avgGain: 76,
        avgMax: 297,
        activeCalls: 20,
        badges: ['crown'],
    },
    {
        username: "rinoa_trades",
        totalTweets: 400,
        totalCalls: 76,
        successfulCalls: 62,
        failedCalls: 14,
        successRate: 82,
        totalRoi: 592,
        avgRoi: 78,
        hypotheticalPnL: 5920,
        calls: [],
        score: 78543,
        rankChange: 1,
        avgGain: 78,
        avgMax: 56,
        activeCalls: 14,
        badges: ['crown'],
    },
    {
        username: "mwt888",
        totalTweets: 300,
        totalCalls: 123,
        successfulCalls: 15,
        failedCalls: 108,
        successRate: 12,
        totalRoi: 222,
        avgRoi: 18,
        hypotheticalPnL: 2220,
        calls: [],
        score: 65432,
        rankChange: 2,
        avgGain: 18,
        avgMax: 33,
        activeCalls: 3,
        badges: ['crown'],
    },
    {
        username: "whatgains",
        totalTweets: 200,
        totalCalls: 142,
        successfulCalls: 64,
        failedCalls: 78,
        successRate: 45,
        totalRoi: 639,
        avgRoi: 45,
        hypotheticalPnL: 6390,
        calls: [],
        score: 59251,
        rankChange: 0,
        avgGain: 45,
        avgMax: 27,
        activeCalls: 7,
        badges: ['star'],
    },
    {
        username: "mikethetrader323",
        totalTweets: 800,
        totalCalls: 267,
        successfulCalls: 149,
        failedCalls: 118,
        successRate: 56,
        totalRoi: 1441,
        avgRoi: 54,
        hypotheticalPnL: 14410,
        calls: [],
        score: 46287,
        rankChange: 2,
        avgGain: 54,
        avgMax: 19,
        activeCalls: 5,
        badges: [],
    },
    {
        username: "icobeast",
        totalTweets: 501,
        totalCalls: 14,
        successfulCalls: 3,
        failedCalls: 11,
        successRate: 21,
        totalRoi: 87,
        avgRoi: 6,
        hypotheticalPnL: 87,
        calls: [],
        score: 3175,
        rankChange: -3,
        avgGain: 6,
        avgMax: 29,
        activeCalls: 1,
        badges: [],
    },
];

export function getInfluencerByUsername(username: string): InfluencerStats | undefined {
    return mockInfluencers.find(i => i.username.toLowerCase() === username.toLowerCase());
}
